export const projectsData = [
  {
    slug: "kitabdukaan-website-seo",
    relatedServiceSlug: "website-development",
    category: "website",
    categoryLabel: "Shopify Website Development & SEO",
    tag: "Shopify + SEO",
    metaIcon: "/img/meta-shopify.svg",
    metaColor: "green",
    image: "/img/projects/kitabdukaan-online-bookstore.svg",
    imageWidth: 1200,
    imageHeight: 800,
    imageAlt: "KitabDukaan.in online bookstore built on Shopify",
    title: "KitabDukaan.in",
    tagline: "Building a modern online bookstore with a strong foundation for organic growth.",
    shortDesc:
      "A Shopify-built online bookstore with organized categories and consistent product listings, backed by on-page and technical SEO for long-term organic growth.",
    externalLink: "https://kitabdukaan.in/",
    challenge:
      "KitabDukaan needed a professional, easy-to-navigate online bookstore and a search-friendly foundation strong enough to support organic growth as a brand-new store in a competitive market.",
    solution:
      "A custom Shopify build with organized book categories, consistent product listings, and a mobile-first shopping experience, paired with keyword-mapped on-page SEO, a technical SEO foundation, and internal linking across category and product pages.",
    result:
      "A fully functional, trustworthy online bookstore with a scalable catalogue and a search-friendly structure, ready to support future content, backlinks, and organic ranking growth.",
    ctaText: "Build Your Online Store",
    content: [
      { type: "h2", text: "Project Overview" },
      { type: "p", text: "KitabDukaan.in is an online bookstore created to make books easily accessible to readers across India. The store offers books from different categories, including self-help, fiction, non-fiction, novels, business, personal development, competitive examinations, children's books and more." },
      { type: "p", text: "KitabDukaan needed more than a basic e-commerce website. The business required a professional online store where customers could explore categories, find relevant books, understand product details and complete their purchases without unnecessary complications." },
      { type: "p", text: "BrandKarlo worked on two important areas of the project:" },
      {
        type: "ul",
        items: [
          "Shopify Website Design and Development",
          "Search Engine Optimization",
        ],
      },
      { type: "p", text: "Our objective was to build a reliable online bookstore while creating a strong SEO foundation for its long-term organic growth." },
      { type: "h2", text: "The Challenge" },
      { type: "p", text: "Before starting the project, KitabDukaan faced several challenges common to new online bookstores." },
      { type: "h3", text: "Website-related challenges" },
      {
        type: "ul",
        items: [
          "The business needed a complete and professional online presence.",
          "A large number of books had to be arranged into proper categories and collections.",
          "Product information needed to be presented in a clear and consistent format.",
          "The website had to work smoothly on mobile phones, tablets and desktop devices.",
          "Customers needed a simple way to browse, search and purchase books.",
          "Important information such as delivery, returns, privacy and terms had to be easily available.",
          "The website needed to build trust despite being a new online bookstore.",
        ],
      },
      { type: "h3", text: "SEO-related challenges" },
      {
        type: "ul",
        items: [
          "The website was new and had limited search engine visibility.",
          "Product and collection pages required search-friendly URLs and content.",
          "Book categories had to be structured around relevant customer searches.",
          "Page titles and meta descriptions needed proper optimization.",
          "Search engines needed a clear structure to discover and understand the website.",
          "The business was entering a competitive online bookselling market.",
          "The website needed an SEO strategy that could support future content and backlink activities.",
        ],
      },
      { type: "h2", text: "Part 1: Website Design and Development" },
      { type: "h3", text: "Our Website Development Approach" },
      { type: "p", text: "BrandKarlo selected Shopify as the e-commerce platform for KitabDukaan because it provides a secure, manageable and scalable system for running an online store." },
      { type: "p", text: "The website was planned around three key priorities:" },
      {
        type: "ul",
        items: [
          "Easy product discovery",
          "Simple shopping experience",
          "Professional and trustworthy presentation",
        ],
      },
      { type: "h3", text: "1. Store Structure and Navigation" },
      { type: "p", text: "We created an organized website structure so visitors could easily explore books according to their interests." },
      { type: "p", text: "Books were arranged into relevant categories and collections, allowing customers to move from the homepage to a category and then to a product without confusion." },
      { type: "p", text: "The navigation was kept simple and customer-friendly. This was particularly important for mobile users, who form a significant part of the Indian e-commerce audience." },
      { type: "h3", text: "2. Shopify Store Development" },
      { type: "p", text: "We developed the online store using Shopify and configured the essential e-commerce functions required to manage and sell books online." },
      { type: "p", text: "The development work included:" },
      {
        type: "ul",
        items: [
          "Shopify theme configuration",
          "Homepage creation",
          "Product-page setup",
          "Category and collection creation",
          "Shopping-cart configuration",
          "Checkout-flow setup",
          "Payment and Cash on Delivery preparation",
          "Mobile-responsive layout",
          "Header and footer development",
          "Policy-page integration",
          "Domain connection",
        ],
      },
      { type: "p", text: "The website was built so the KitabDukaan team could manage products, inventory, prices and collections without needing advanced technical knowledge." },
      { type: "h3", text: "3. Product Listing and Catalogue Organization" },
      { type: "p", text: "An online bookstore can quickly become difficult to navigate if products are not properly organized. We therefore developed a consistent product-listing system for the store." },
      { type: "p", text: "Each listing was structured to include relevant information such as:" },
      {
        type: "ul",
        items: [
          "Book title",
          "Author or publisher",
          "Product images",
          "Selling price",
          "Book description",
          "Availability",
          "Relevant category",
          "Product tags",
        ],
      },
      { type: "p", text: "Consistent product data improves the customer experience and makes future catalogue management easier." },
      { type: "h3", text: "4. Mobile-Responsive Shopping Experience" },
      { type: "p", text: "The website was optimized for different screen sizes so visitors could browse and purchase books using smartphones, tablets and computers." },
      { type: "p", text: "Special attention was given to:" },
      {
        type: "ul",
        items: [
          "Readable text",
          "Clear product images",
          "Easy-to-use navigation",
          "Visible action buttons",
          "Proper spacing",
          "Mobile-friendly product pages",
          "Smooth cart and checkout experience",
        ],
      },
      { type: "p", text: "The objective was to reduce confusion and help visitors reach the required product with fewer steps." },
      { type: "h3", text: "5. Trust-Building Elements" },
      { type: "p", text: "Customers are often cautious when purchasing from a new online store. To improve credibility, we included essential business and policy information across the website." },
      { type: "p", text: "The store includes or supports important pages such as:" },
      {
        type: "ul",
        items: [
          "About Us",
          "Contact Us",
          "Privacy Policy",
          "Terms and Conditions",
          "Shipping Policy",
          "Return and Replacement Policy",
        ],
      },
      { type: "p", text: "These pages help visitors understand the business, its processes and their rights before completing an order." },
      { type: "h3", text: "6. Conversion-Focused User Experience" },
      { type: "p", text: "The website was designed to guide visitors towards taking meaningful actions, such as exploring a collection, opening a product, adding a book to the cart or completing a purchase." },
      { type: "p", text: "We used clear product presentation, structured collections and visible calls to action to create a more direct shopping journey." },
      { type: "h2", text: "Part 2: Search Engine Optimization" },
      { type: "h3", text: "Our SEO Approach" },
      { type: "p", text: "After developing the website, BrandKarlo worked on establishing its basic search engine foundation." },
      { type: "p", text: "The purpose of this stage was to help search engines properly crawl, understand and index the website while preparing it for future organic growth." },
      { type: "h3", text: "1. Keyword and Search-Intent Planning" },
      { type: "p", text: "We identified keyword opportunities related to the products and categories available on KitabDukaan." },
      { type: "p", text: "The keyword strategy focused on searches connected with:" },
      {
        type: "ul",
        items: [
          "Buying books online",
          "Online bookstores in India",
          "Self-help books",
          "Fiction and non-fiction books",
          "Popular novels",
          "Business and personal-development books",
          "Category-specific book searches",
        ],
      },
      { type: "p", text: "Instead of using the same broad keyword on every page, relevant search terms were assigned according to each page's purpose." },
      { type: "h3", text: "2. Collection and Category Optimization" },
      { type: "p", text: "Collection pages are important for both customers and search engines. We organized the store into meaningful book categories and prepared them for category-specific optimization." },
      { type: "p", text: "This structure helps search engines understand the relationship between the homepage, collections and individual products." },
      { type: "p", text: "It also gives the website opportunities to appear for searches that may not include a specific book title but show clear buying interest." },
      { type: "h3", text: "3. On-Page SEO" },
      { type: "p", text: "Important pages were prepared using essential on-page SEO practices, including:" },
      {
        type: "ul",
        items: [
          "Search-friendly page titles",
          "Relevant meta descriptions",
          "Proper heading structure",
          "Clean and understandable URLs",
          "Product-focused content",
          "Image alternative text",
          "Internal links between related pages",
          "Natural keyword placement",
        ],
      },
      { type: "p", text: "The goal was to optimize pages for search engines without making the content sound repetitive or unnatural to customers." },
      { type: "h3", text: "4. Technical SEO Foundation" },
      { type: "p", text: "The technical setup was reviewed to support search-engine accessibility and website performance." },
      { type: "p", text: "The work focused on areas such as:" },
      {
        type: "ul",
        items: [
          "Mobile responsiveness",
          "Secure HTTPS connection",
          "Logical website architecture",
          "Search-engine-friendly URLs",
          "Sitemap availability",
          "Indexing preparation",
          "Broken-link prevention",
          "Image optimization",
          "Page-performance improvement",
        ],
      },
      { type: "p", text: "A technically healthy website gives SEO campaigns a stronger base and helps prevent avoidable crawling or usability problems." },
      { type: "h3", text: "5. Internal Linking" },
      { type: "p", text: "We created a logical connection between important website sections, categories and product pages." },
      { type: "p", text: "Internal linking helps customers discover additional books and allows search engines to find deeper pages of the website. It also communicates which categories and pages are most important." },
      { type: "h3", text: "6. Content Growth Strategy" },
      { type: "p", text: "SEO for an online bookstore requires continuous improvement. Therefore, the website was structured to support future content creation." },
      { type: "p", text: "Recommended content opportunities include:" },
      {
        type: "ul",
        items: [
          "Best books to read by category",
          "Book recommendations for beginners",
          "Self-help book guides",
          "Author-focused collections",
          "New book releases",
          "Reading lists",
          "Book comparisons and reviews",
          "Gift guides for readers",
        ],
      },
      { type: "p", text: "This type of content can attract informational searches and guide readers towards relevant products." },
      { type: "h2", text: "Project Outcome" },
      { type: "p", text: "BrandKarlo successfully transformed the KitabDukaan concept into a functional and professionally structured online bookstore." },
      { type: "p", text: "The completed project provided:" },
      {
        type: "ul",
        items: [
          "A modern Shopify-based e-commerce website",
          "Organized book categories and collections",
          "Consistent product listings",
          "Responsive design for mobile and desktop devices",
          "Simplified product discovery and purchasing",
          "Important policy and trust pages",
          "A search-friendly website structure",
          "Optimized foundations for future organic growth",
          "A manageable backend for products and inventory",
          "A scalable platform that can grow with the business",
        ],
      },
      { type: "p", text: "As this is a developing e-commerce project, long-term traffic, keyword-ranking and sales results will depend on continued content publishing, catalogue expansion, link building and regular SEO improvements." },
      { type: "h2", text: "Technologies and Services Used" },
      {
        type: "ul",
        items: [
          "Shopify",
          "E-commerce Website Development",
          "Responsive Web Design",
          "Product Catalogue Management",
          "Collection and Category Setup",
          "On-Page SEO",
          "Technical SEO",
          "Keyword Planning",
          "Internal Linking",
          "Search-Friendly Content Structure",
        ],
      },
      { type: "h2", text: "Conclusion" },
      { type: "p", text: "The KitabDukaan.in project demonstrates how website development and SEO work together to create a stronger e-commerce business." },
      { type: "p", text: "A visually attractive website alone is not enough if customers cannot navigate it or search engines cannot understand it. Similarly, SEO cannot deliver its full potential when the website has a confusing structure or poor shopping experience." },
      { type: "p", text: "By combining Shopify website development, organized product listings, mobile-responsive design and essential SEO practices, BrandKarlo created a solid digital foundation for KitabDukaan." },
      { type: "p", text: "The store is now prepared to expand its catalogue, publish useful reading content, target more book-related searches and build a stronger presence in India's online book market." },
    ],
  },
];

export function getProjectBySlug(slug) {
  return projectsData.find((p) => p.slug === slug);
}

export function getRelatedProjects(currentSlug, limit = 3) {
  const current = getProjectBySlug(currentSlug);
  if (!current) return projectsData.filter((p) => p.slug !== currentSlug).slice(0, limit);

  const sameCategory = projectsData.filter(
    (p) => p.slug !== currentSlug && p.category === current.category
  );
  const others = projectsData.filter(
    (p) => p.slug !== currentSlug && p.category !== current.category
  );

  return [...sameCategory, ...others].slice(0, limit);
}
